const KEY="KONOHA_LIVELY_CHECKLIST_TASKSYNC_V1";
const DEFAULT_DAILY=["Check emails / messages","Send morning update","Check Jira / assigned tasks","Update task progress","Send evening update"];
const DEFAULT_WEEKLY=["WSR – Email","WSR – Message","Fill Timesheet"];

// Paste the SAME deployed Apps Script /exec URL here and in mobile/script.js.
const SHEETS_WEB_APP_URL="https://script.google.com/macros/s/AKfycbwN-3y4Dg8R4IXa0TPcXpy9k6nVBuVM2w4qqgtqS_uednFrAeMtyjbaEkHaAVjeGdY2/exec";
const SHEETS_ENABLED=SHEETS_WEB_APP_URL.startsWith("https://script.google.com/");
const DEVICE_NAME="Laptop";

function dk(){const d=new Date();return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function weekKeyForDate(key){const d=new Date(key+"T12:00:00"),day=d.getDay();d.setDate(d.getDate()+(day===0?-6:1-day));return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`}
function wk(){return weekKeyForDate(dk())}
function dailyDefaults(){return DEFAULT_DAILY.map((text,i)=>({id:"d"+i,text,done:false}))}
function weeklyDefaults(){return DEFAULT_WEEKLY.map((text,i)=>({id:"w"+i,text,done:false}))}
function validRemoteTasks(arr){return Array.isArray(arr)&&arr.length>0&&arr.every(x=>x&&typeof x.id==="string"&&x.id&&typeof x.text==="string"&&x.text.trim())}
function init(){let d;try{d=JSON.parse(localStorage.getItem(KEY)||"null")}catch(e){}if(!d)d={daily:dailyDefaults(),dailyDate:dk(),days:{},weeks:{},pos:{},notesByDay:{}};d.days??={};d.weeks??={};d.pos??={};d.notesByDay??={};if(d.dailyDate!==dk()||!Array.isArray(d.daily)||d.daily.length===0){d.daily=dailyDefaults();d.dailyDate=dk()}if(!d.days[dk()]||!Array.isArray(d.days[dk()].tasks))d.days[dk()]={tasks:[]};if(!d.weeks[wk()]||!Array.isArray(d.weeks[wk()].tasks)||d.weeks[wk()].tasks.length===0)d.weeks[wk()]={tasks:weeklyDefaults()};return d}
let data=init();let lastKnownDay=dk();let pullBusy=false;

function persist(){localStorage.setItem(KEY,JSON.stringify(data))}
function saveLocal(){persist();render()}
function list(t){return t==="daily"?data.daily:t==="weekly"?data.weeks[wk()].tasks:data.days[dk()].tasks}
function categoryName(t){return t==="daily"?"Daily":t==="weekly"?"Weekly":"Today"}
function esc(s){return String(s).replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]))}
function renderList(t,id){document.getElementById(id).innerHTML=list(t).map(x=>`<div class="task ${x.done?"done":""}"><input type="checkbox" ${x.done?"checked":""} onchange="toggle('${t}','${x.id}')"><input type="text" value="${esc(x.text)}" onchange="editTask('${t}','${x.id}',this.value)"><button class="delete" onclick="removeTask('${t}','${x.id}')">×</button></div>`).join("")}
function stat(t){const a=list(t),n=a.filter(x=>x.done).length;return[n,a.length,a.length?Math.round(n/a.length*100):0]}
function render(){const d=new Date();weekday.textContent=d.toLocaleDateString(undefined,{weekday:"long"}).toUpperCase();daynum.textContent=d.getDate();month.textContent=d.toLocaleDateString(undefined,{month:"long",year:"numeric"}).toUpperCase();clock.textContent=d.toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"});renderList("daily","dailyList");renderList("today","todayList");renderList("weekly","weeklyList");[["daily","daily"],["today","today"],["weekly","weekly"]].forEach(([t,id])=>{const[s,n,p]=stat(t);document.getElementById(id+"Progress").textContent=`${s} / ${n} Completed`;document.getElementById(id+"Pct").textContent=p+"%";document.getElementById(id+"Bar").style.width=p+"%"});const a=stat("daily"),b=stat("today"),c=stat("weekly"),tot=a[1]+b[1]+c[1],done=a[0]+b[0]+c[0],p=tot?Math.round(done/tot*100):0;dailyStat.textContent=`${a[0]} / ${a[1]}`;todayStat.textContent=`${b[0]} / ${b[1]}`;weeklyStat.textContent=`${c[0]} / ${c[1]}`;overallPct.textContent=p+"%";document.querySelector(".ring").style.setProperty("--deg",p*3.6+"deg");renderWeek();applyPositions()}
function renderWeek(){const box=document.getElementById("weekDays"),base=new Date(),n=(base.getDay()+6)%7;box.innerHTML="";for(let i=0;i<7;i++){const d=new Date(base);d.setDate(base.getDate()-n+i);const k=`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,"0")}-${String(d.getDate()).padStart(2,"0")}`,a=data.days[k]?.tasks||[],p=a.length?Math.round(a.filter(x=>x.done).length/a.length*100):0,e=document.createElement("div");e.className="week-day "+(i===n?"current":"");e.innerHTML=`${d.toLocaleDateString(undefined,{weekday:"short"})}<strong>${d.getDate()}</strong><small>${p}%</small>`;box.appendChild(e)}}

function toggle(t,id){const x=list(t).find(a=>a.id===id);if(!x)return;x.done=!x.done;saveLocal();sendTask(t,x)}
function editTask(t,id,v){const x=list(t).find(a=>a.id===id);if(!x)return;x.text=v.trim()||"Untitled task";saveLocal();sendTask(t,x)}
function removeTask(t,id){const a=list(t),i=a.findIndex(x=>x.id===id);if(i<0)return;a.splice(i,1);saveLocal();sendDelete(t,id)}
function addTask(t){const el=document.getElementById(t+"Input"),v=el.value.trim();if(!v)return;const x={id:t[0]+Date.now()+Math.random().toString(36).slice(2,7),text:v,done:false};list(t).push(x);el.value="";saveLocal();sendTask(t,x);toast("Task added")}
function enterAdd(e,t){if(e.key==="Enter")addTask(t)}
function focusAdd(t){document.getElementById(t+"Input").focus()}
function resetToday(){data.daily=dailyDefaults();data.dailyDate=dk();data.days[dk()]={tasks:[]};saveLocal();postNoCors({action:"reset",target:"today",date:dk(),week:wk(),device:DEVICE_NAME}).then(()=>setTimeout(pullLiveState,700));toast("Today reset")}
function resetWeek(){data.weeks[wk()]={tasks:weeklyDefaults()};saveLocal();postNoCors({action:"reset",target:"week",date:dk(),week:wk(),device:DEVICE_NAME}).then(()=>setTimeout(pullLiveState,700));toast("Week reset")}
function toast(s){const x=document.getElementById("toast");x.textContent=s;x.style.opacity=1;clearTimeout(window._t);window._t=setTimeout(()=>x.style.opacity=0,1200)}

function setSyncStatus(text,cls=""){const el=document.getElementById("syncStatus");if(!el)return;el.textContent=text;el.className="sync-status "+cls}
function postNoCors(payload){if(!SHEETS_ENABLED)return Promise.reject(new Error("Apps Script URL missing"));return fetch(SHEETS_WEB_APP_URL,{method:"POST",mode:"no-cors",headers:{"Content-Type":"text/plain;charset=utf-8"},body:JSON.stringify(payload),keepalive:true})}
function sendTask(t,x){setSyncStatus("☁ Updating task…","busy");postNoCors({action:"task",date:dk(),week:wk(),category:categoryName(t),task:{id:x.id,text:x.text,done:!!x.done},device:DEVICE_NAME}).then(()=>setSyncStatus("☁ Task queued","ok")).catch(()=>setSyncStatus("☁ Sync failed","err"))}
function sendDelete(t,id){setSyncStatus("☁ Deleting task…","busy");postNoCors({action:"deleteTask",date:dk(),week:wk(),category:categoryName(t),id,device:DEVICE_NAME}).then(()=>setSyncStatus("☁ Delete queued","ok")).catch(()=>setSyncStatus("☁ Sync failed","err"))}
function sendNotes(notesText){postNoCors({action:"notes",date:dk(),notes:notesText,device:DEVICE_NAME}).then(()=>setSyncStatus("☁ Notes queued","ok")).catch(()=>setSyncStatus("☁ Notes sync failed","err"))}

function pullLiveState(){if(!SHEETS_ENABLED||pullBusy)return;pullBusy=true;setSyncStatus("☁ Checking shared state…","busy");const cb="__konohaState_"+Date.now();let called=false;const s=document.createElement("script");window[cb]=resp=>{called=true;try{if(resp&&resp.success)applyRemoteState(resp);else throw new Error(resp?.error||"No state")}catch(e){console.error(e);setSyncStatus("☁ Read failed","err")}finally{cleanup()}};function cleanup(){pullBusy=false;delete window[cb];s.remove()}s.src=`${SHEETS_WEB_APP_URL}?action=state&date=${encodeURIComponent(dk())}&week=${encodeURIComponent(wk())}&callback=${encodeURIComponent(cb)}&_=${Date.now()}`;s.onerror=()=>{setSyncStatus("☁ Access blocked","err");cleanup()};s.onload=()=>setTimeout(()=>{if(!called){setSyncStatus("☁ Sign-in/access blocked","err");cleanup()}},1500);document.head.appendChild(s)}
function applyRemoteState(resp){const t=resp&&resp.tasks?resp.tasks:{};let changed=false;if(validRemoteTasks(t.daily)){data.daily=t.daily;data.dailyDate=dk();changed=true}else if(!Array.isArray(data.daily)||data.daily.length===0){data.daily=dailyDefaults();data.dailyDate=dk();data.daily.forEach(x=>sendTask("daily",x))}if(!data.days[dk()])data.days[dk()]={tasks:[]};if(Array.isArray(t.today)){data.days[dk()].tasks=t.today.filter(x=>x&&typeof x.id==="string"&&typeof x.text==="string");changed=true}if(!data.weeks[wk()])data.weeks[wk()]={tasks:weeklyDefaults()};if(validRemoteTasks(t.weekly)){data.weeks[wk()].tasks=t.weekly;changed=true}else if(!Array.isArray(data.weeks[wk()].tasks)||data.weeks[wk()].tasks.length===0){data.weeks[wk()].tasks=weeklyDefaults();data.weeks[wk()].tasks.forEach(x=>sendTask("weekly",x))}data.notesByDay??={};if(typeof resp.notes==="string")data.notesByDay[dk()]=resp.notes;persist();render();const n=document.getElementById("notes");if(n&&document.activeElement!==n)n.value=data.notesByDay[dk()]||"";setSyncStatus(changed?"☁ Synced with Sheets":"☁ Local defaults kept","ok")}

function calculateForTasks(a){const done=a.filter(x=>x.done).length;return{done,total:a.length,pct:a.length?Math.round(done/a.length*100):0}}
function buildDailyReport(dateKey){const daily=calculateForTasks(data.daily),today=calculateForTasks(data.days[dateKey]?.tasks||[]),weekly=calculateForTasks(data.weeks[weekKeyForDate(dateKey)]?.tasks||[]),total=daily.total+today.total+weekly.total,done=daily.done+today.done+weekly.done;return{date:dateKey,day:new Date(dateKey+"T12:00:00").toLocaleDateString(undefined,{weekday:"long"}),dailyPct:daily.pct,todayPct:today.pct,weeklyPct:weekly.pct,overallPct:total?Math.round(done/total*100):0,completed:done,missed:Math.max(0,total-done),notes:data.notesByDay?.[dateKey]||"",tasks:[...data.daily.map(x=>({category:"Daily",text:x.text,done:x.done})),...(data.days[dateKey]?.tasks||[]).map(x=>({category:"Today",text:x.text,done:x.done})),...(data.weeks[weekKeyForDate(dateKey)]?.tasks||[]).map(x=>({category:"Weekly",text:x.text,done:x.done}))]}}
function saveReportToSheets(dateKey=dk()){data.notesByDay??={};data.notesByDay[dk()]=document.getElementById("notes").value;persist();setSyncStatus("☁ Saving history…","busy");postNoCors({action:"snapshot",...buildDailyReport(dateKey)}).then(()=>{localStorage.setItem(KEY+"_lastSheetSave",dateKey);setSyncStatus("☁ History queued","ok")}).catch(()=>setSyncStatus("☁ History save failed","err"))}

function installNotes(){data.notesByDay??={};const el=document.getElementById("notes");el.value=data.notesByDay[dk()]||"";let timer;el.addEventListener("input",()=>{data.notesByDay[dk()]=el.value;persist();clearTimeout(timer);timer=setTimeout(()=>sendNotes(el.value),700)})}
function setupDragging(){document.querySelectorAll(".widget").forEach(w=>{const bar=w.querySelector(".dragbar"),grip=w.querySelector(".resize-handle");let drag=false,sx=0,sy=0,ox=0,oy=0;bar.addEventListener("pointerdown",e=>{if(e.target.closest("button,input,textarea"))return;drag=true;bar.setPointerCapture(e.pointerId);const r=w.getBoundingClientRect();sx=e.clientX;sy=e.clientY;ox=r.left;oy=r.top;w.style.zIndex=++window.z});bar.addEventListener("pointermove",e=>{if(!drag)return;w.style.left=Math.max(0,Math.min(innerWidth-w.offsetWidth,ox+e.clientX-sx))+"px";w.style.top=Math.max(0,Math.min(innerHeight-w.offsetHeight,oy+e.clientY-sy))+"px";w.style.right="auto";w.style.bottom="auto"});bar.addEventListener("pointerup",()=>{if(!drag)return;drag=false;saveWidgetGeometry(w)});if(grip){let resizing=false,rsx=0,rsy=0,rw=0,rh=0;grip.addEventListener("pointerdown",e=>{e.preventDefault();e.stopPropagation();resizing=true;grip.setPointerCapture(e.pointerId);const r=w.getBoundingClientRect();rsx=e.clientX;rsy=e.clientY;rw=r.width;rh=r.height;w.style.zIndex=++window.z});grip.addEventListener("pointermove",e=>{if(!resizing)return;const r=w.getBoundingClientRect();w.style.width=Math.max(180,Math.min(innerWidth-r.left-4,rw+e.clientX-rsx))+"px";w.style.height=Math.max(120,Math.min(innerHeight-r.top-4,rh+e.clientY-rsy))+"px"});grip.addEventListener("pointerup",()=>{if(!resizing)return;resizing=false;saveWidgetGeometry(w)})}})}
function saveWidgetGeometry(w){const r=w.getBoundingClientRect();data.pos[w.dataset.widget]??={};Object.assign(data.pos[w.dataset.widget],{x:r.left/innerWidth,y:r.top/innerHeight,width:r.width/innerWidth,height:r.height/innerHeight});persist()}
window.z=10;function applyPositions(){document.querySelectorAll(".widget").forEach(w=>{const p=data.pos[w.dataset.widget];if(p){w.style.left=p.x*innerWidth+"px";w.style.top=p.y*innerHeight+"px";w.style.right="auto";w.style.bottom="auto";if(p.width)w.style.width=p.width*innerWidth+"px";if(p.height)w.style.height=p.height*innerHeight+"px"}})}

installNotes();setupDragging();render();pullLiveState();
setInterval(()=>{const d=new Date();weekday.textContent=d.toLocaleDateString(undefined,{weekday:"long"}).toUpperCase();daynum.textContent=d.getDate();month.textContent=d.toLocaleDateString(undefined,{month:"long",year:"numeric"}).toUpperCase();clock.textContent=d.toLocaleTimeString(undefined,{hour:"2-digit",minute:"2-digit"})},1000);
setInterval(pullLiveState,5000);
document.addEventListener("visibilitychange",()=>{if(!document.hidden)pullLiveState()});
setInterval(()=>{if(dk()!==lastKnownDay){const old=lastKnownDay;postNoCors({action:"snapshot",...buildDailyReport(old)}).catch(()=>{});lastKnownDay=dk();location.reload()}},30000);
document.documentElement.style.cursor="default";document.body.style.cursor="default";
